version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./autoru_catalog/Dockerfile
    restart: always
    container_name: web
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             exec gunicorn core.wsgi:application -b 0.0.0.0:$WEB_PORT --log-level debug"
    volumes:
      - autoru_catalog_static_value:/app/web-static/
      - autoru_catalog_media_value:/app/web-media/
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  autoru_catalog_static_value:
    name: autoru_catalog_static_value
  autoru_catalog_media_value:
    name: autoru_catalog_media_value